import type { Metadata } from "next";
import { Sofia, Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const sofia = Sofia({
  weight: "400",
  variable: "--font-sofia-regular",
  subsets:["latin"]
});

export const metadata: Metadata = {
  title: "Agrodoa",
  description: "Generated by create next app",
  icons:{
    icon: "/logo.png"
  }
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerBen = ["Inicio", "Causas", "Perfil"]

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sofia.variable} antialiased bg-primary`}>
        <header className="w-full h-16 bg-secondary items-center justify-between flex flex-row-reverse">
          <ul className="flex gap-4 px-4 text-2xl ">
            {headerBen.map((item) => (
              <Link href={item} key={item}>{item}</Link>
            ))}
          </ul>
          <div className="flex items-center px-4">
          <Image src="/logo.png" height={64} width={64} alt="Logo imagem"></Image>
          <span className={sofia.className }>Agrodoa</span>
        </div>
        </header>
        <main className="p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
